apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - metrics-server.yaml
  - cloudnative-pg.yaml
  - mariadb-operator.yaml
  - mariadb.yaml
  - external-secrets.yaml
  - external-dns.yaml
  - longhorn.yaml
  - longhorn-route.yaml
  - longhorn-auth.yaml
  - oidc-rbac.yaml
  - monitoring/flux.yaml
  - monitoring-collectors.yaml
  - cert-manager.yaml
  - cert-manager-issuer.yaml
  - contour.yaml
  - contour-gateway.yaml
