apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-amedsaude-com-br
spec:
  dnsNames:
    - "*.amedsaude.com.br"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: wildcard-amedsaude-com-br-tls-cert
