apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  interval: 10m
  timeout: 5m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '80.14.4'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: flux-kube-state-metrics-config
      valuesKey: kube-state-metrics-config.yaml
  values:
    prometheus:
      ingress:
        enabled: false
      prometheusSpec:
        enableRemoteWriteReceiver: true
        externalLabels:
          cluster: tools
          environment: tools
        remoteWrite:
          - url: http://mimir.monitoring.svc.cluster.local:8080/api/v1/push
        podMonitorNamespaceSelector: {}
        podMonitorSelector:
          matchLabels:
            app.kubernetes.io/component: monitoring
        retention: 3d
        retentionSize: 14GB
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: longhorn
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 15Gi
    defaultRules:
      create: true
      rules:
        alertmanager: true
        etcd: false
        configReloaders: true
        general: true
        k8s: true
        kubeApiserverAvailability: true
        kubeApiserverBurnrate: true
        kubeApiserverHistogram: true
        kubeApiserverSlos: true
        kubeControllerManager: false
        kubelet: false
        kubeProxy: false
        kubePrometheusGeneral: true
        kubePrometheusNodeRecording: true
        kubernetesApps: true
        kubernetesResources: true
        kubernetesStorage: true
        kubernetesSystem: false
        kubeSchedulerAlerting: false
        kubeStateMetrics: true
        network: true
        node: true
        nodeExporterAlerting: true
        nodeExporterRecording: true
        prometheus: true
        prometheusOperator: true
    grafana:
      enabled: false
      forceDeployDashboards: true
      namespaceOverride: grafana
      forceDeployDatasources: true
      sidecar:
        dashboards:
          annotations:
            grafana_folder: Kubernetes
    alertmanager:
      alertmanagerSpec: {}
      config:
        inhibit_rules:
          - source_matchers:
              - "alertname = InfoInhibitor"
            target_matchers:
              - "severity = info"
            equal:
              - "namespace"
        route:
          group_by: ["namespace"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 12h
          receiver: "null"
          routes:
            - receiver: "null"
              matchers:
                - alertname =~ "InfoInhibitor|Watchdog"
        receivers:
          - name: "null"
