apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - namespace.yaml
  - secret.yaml
  - helm.yaml
  - httproute.yaml
configMapGenerator:
  - name: fluxcd-dashboards
    files:
      - dashboards/fluxcd/fluxcd-control-plane.json
      - dashboards/fluxcd/fluxcd-cluster.json
    options:
      annotations:
        grafana_folder: FluxCD
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: flux
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: bkw-dashboards
    files:
      - dashboards/bkw/bkw.json
    options:
      annotations:
        grafana_folder: BKW
      labels:
        grafana_dashboard: "1"
        kustomize.toolkit.fluxcd.io/substitute: disabled
