apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: longhorn-backup-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      mergePolicy: Merge
      data:
        VIRTUAL_HOSTED_STYLE: "false"
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: longhorn-backup-access-key
        version: CURRENT
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: longhorn-backup-secret-key
        version: CURRENT
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: longhorn-backup-endpoint
        version: CURRENT
