apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-object-storage-backup
spec:
  cron: "0 2 * * *"
  task: backup
  groups:
    - default
  retain: 7
  concurrency: 1
  parameters:
    full-backup-interval: "7"
