apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-postgres-backup-credentials
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: keycloak-postgres-backup-credentials
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: longhorn-backup-access-key
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: longhorn-backup-secret-key
