apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 5m
  url: https://kubernetes-sigs.github.io/external-dns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: external-dns
      version: "1.20.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
      interval: 5m
  releaseName: external-dns
  values:
    provider:
      name: cloudflare
    policy: sync
    sources:
      - service
      - ingress
      - crd
      - gateway-httproute
    managedRecordTypes:
      - A
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-config
            key: apiKey
    extraArgs:
      - --exclude-target-net=10.0.0.0/8
      - --domain-filter=amedsaude.com.br
      - --domain-filter=amedpy.com
      - --domain-filter=cms-sync.com.br
      - --domain-filter=coomedms.com.br
      - --domain-filter=drpap.com.br
      - --domain-filter=drpap.uy
      - --domain-filter=helppap.com
      - --domain-filter=infectoassist.com.br
      - --domain-filter=inovapap.com.br
      - --domain-filter=monitoramentoemsaude.com.br
      - --domain-filter=moveye.com.br
      - --domain-filter=papeduca.com.br
      - --domain-filter=papensino.com.br
      - --domain-filter=papescala.com.br
      - --domain-filter=papinfecto.com.br
      - --domain-filter=pap-sync.com.br
      - --domain-filter=perreabilita.com.br
      - --domain-filter=qualiassist.com.br
      - --txt-owner-id=${EXTERNALDNS_TXT_OWNER_ID:=core}
