apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-postgres-plugin
  namespace: flux-system
spec:
  interval: 10m
  path: ./gitops/core/keycloak-postgres/plugin
  prune: true
  dependsOn:
    - name: cloudnative-pg
    - name: cert-manager
  sourceRef:
    kind: GitRepository
    name: flux-system
