apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - metrics-server.yaml
  - olm.yaml
  - keycloak-operator.yaml
  - cloudnative-pg.yaml
  - keycloak-postgres-plugin.yaml
  - keycloak-postgres.yaml
  - external-secrets.yaml
  - cert-manager.yaml
  - cert-manager-issuer.yaml
  - contour.yaml
  - contour-gateway.yaml
  - longhorn.yaml
  - longhorn-route.yaml
  - grafana/flux.yaml
