apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana
  namespace: grafana
spec:
  interval: 10m
  timeout: 5m
  targetNamespace: grafana
  chart:
    spec:
      chart: grafana
      version: "10.5.15"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: grafana
      interval: 5m
  releaseName: grafana
  values:
    admin:
      existingSecret: grafana-admin-credentials
      userKey: admin-user
      passwordKey: admin-password
    service:
      type: ClusterIP
    persistence:
      enabled: false
    grafana.ini:
      app_mode: production
      server:
        domain: grafana-inova.hackyard.dev
        root_url: https://grafana-inova.hackyard.dev
      users:
        allow_sign_up: false
      auth:
        disable_login_form: true
      auth.generic_oauth:
        enabled: true
        name: Keycloak
        allow_sign_up: false
        client_id: $__file{/etc/secrets/keycloak_client/client-id}
        client_secret: $__file{/etc/secrets/keycloak_client/client-secret}
        scopes: openid profile email groups
        email_attribute_path: email
        auth_url: https://keycloak-inova.hackyard.dev/realms/platform/protocol/openid-connect/auth
        token_url: https://keycloak-inova.hackyard.dev/realms/platform/protocol/openid-connect/token
        api_url: https://keycloak-inova.hackyard.dev/realms/platform/protocol/openid-connect/userinfo
        role_attribute_path: contains(groups[*], 'platform-admins') && 'Admin' || 'Viewer'
    extraSecretMounts:
      - name: keycloak-client
        secretName: grafana-keycloak-client
        defaultMode: 0440
        mountPath: /etc/secrets/keycloak_client
        readOnly: true
    plugins:
      - oci-metrics-datasource
