apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: grafana
resources:
  - namespace.yaml
  - secret.yaml
  - helm.yaml
  - httproute.yaml
configMapGenerator:
  - name: kubernetes-dashboards
    files:
      - dashboards/kubernetes/fleet-overview.json
      - dashboards/kubernetes/cluster-resources.json
    options:
      annotations:
        grafana_folder: Kubernetes
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: observability
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: mimir-dashboards
    files:
      - dashboards/mimir/mimir-prometheus.json
    options:
      annotations:
        grafana_folder: Mimir
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: observability
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: platform-dashboards
    files:
      - dashboards/platform/platform-operations.json
    options:
      annotations:
        grafana_folder: Platform
      labels:
        grafana_dashboard: "1"
        app.kubernetes.io/part-of: observability
        kustomize.toolkit.fluxcd.io/substitute: disabled
