apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        admin-user: admin
        admin-password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: grafana-tools-admin-password
        version: CURRENT
        decodingStrategy: None
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-keycloak-client
  namespace: grafana
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: grafana-keycloak-client
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-id: grafana
        client-secret: "{{ .client_secret }}"
  data:
    - secretKey: client_secret
      remoteRef:
        key: grafana-keycloak-client
        version: CURRENT
        decodingStrategy: None
