apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-backup-credentials
  namespace: mariadb
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: mariadb-backup-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: access-key-id
      remoteRef:
        key: longhorn-backup-access-key
        version: CURRENT
    - secretKey: secret-access-key
      remoteRef:
        key: longhorn-backup-secret-key
        version: CURRENT
