apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-bootstrap-admin
  namespace: keycloak
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: keycloak-bootstrap-admin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: admin
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: keycloak-tools-admin-password
        version: CURRENT
