output "drg_id" {
  value = oci_core_drg.this.id
}

output "drg_route_table_id" {
  description = "Autogenerated VCN route table used for full-mesh VCN routing"
  value       = oci_core_drg.this.default_drg_route_tables[0].vcn
}
