{
 "title": "Kubernetes Networking Workload (Fleet)",
 "tags": [
  "kubernetes",
  "networking",
  "workload",
  "fleet",
  "mimir"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values(kube_pod_info, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kube_pod_info{environment=~\"$environment\"}, cluster)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{environment=~\"$environment\",cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{environment=~\"$environment\",cluster=~\"$cluster\",namespace=~\"$namespace\"}, workload)"
   },
   {
    "name": "workload_type",
    "label": "Workload type",
    "query": "label_values(namespace_workload_pod:kube_pod_owner:relabel{environment=~\"$environment\",cluster=~\"$cluster\",namespace=~\"$namespace\"}, workload_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes received",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_network_receive_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",environment=~\"$environment\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on (environment,cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{environment=~\"$environment\",cluster=~\"$cluster\",namespace=~\"$namespace\",workload=~\"$workload\",workload_type=~\"$workload_type\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes transmitted",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sort_desc(sum(rate(container_network_transmit_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",environment=~\"$environment\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on (environment,cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{environment=~\"$environment\",cluster=~\"$cluster\",namespace=~\"$namespace\",workload=~\"$workload\",workload_type=~\"$workload_type\"}) by (pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Receive bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",environment=~\"$environment\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on (environment,cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{environment=~\"$environment\",cluster=~\"$cluster\",namespace=~\"$namespace\",workload=~\"$workload\",workload_type=~\"$workload_type\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Transmit bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{job=\"kubelet\",metrics_path=\"/metrics/cadvisor\",environment=~\"$environment\",cluster=~\"$cluster\",namespace=~\"$namespace\"}[$__rate_interval]) * on (environment,cluster,namespace,pod) group_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{environment=~\"$environment\",cluster=~\"$cluster\",namespace=~\"$namespace\",workload=~\"$workload\",workload_type=~\"$workload_type\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}