apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux-system
  labels:
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - helm-controller
          - source-controller
          - kustomize-controller
          - notification-controller
          - image-automation-controller
          - image-reflector-controller
  podMetricsEndpoints:
    - port: http-prom
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: longhorn-backend
  labels:
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - longhorn
  selector:
    matchLabels:
      app: longhorn-manager
  endpoints:
    - targetPort: 9500
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cert-manager
  labels:
    app.kubernetes.io/component: monitoring
spec:
  namespaceSelector:
    matchNames:
      - cert-manager
  selector:
    matchLabels:
      app: cert-manager
  endpoints:
    - targetPort: 9402
      path: /metrics
