apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mariadb-root-password
  namespace: mariadb
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: mariadb-root
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: root-password
      remoteRef:
        key: mariadb-production-root-password
        version: CURRENT
