apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-keycloak-client
  namespace: longhorn
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: longhorn-keycloak-client
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        client-id: longhorn-staging
        client-secret: "{{ .client_secret }}"
        cookie-secret: "{{ .cookie_secret }}"
  data:
    - secretKey: client_secret
      remoteRef:
        key: longhorn-staging-keycloak-client
        version: CURRENT
        decodingStrategy: None
    - secretKey: cookie_secret
      remoteRef:
        key: longhorn-staging-cookie-secret
        version: CURRENT
        decodingStrategy: None
