variable "compartment_id" {
  type        = string
  description = "Compartment where the cluster VCN is created"
}

variable "cluster_name" {
  type        = string
  description = "Cluster name used in OCI resource names"
}

variable "region" {
  type        = string
  description = "OCI region"
}

variable "vcn_cidr" {
  type        = string
  description = "CIDR range for this cluster VCN"
}

variable "public_subnet_cidr" {
  type        = string
  description = "CIDR range for the public subnet"
}

variable "private_subnet_cidr" {
  type        = string
  description = "CIDR range for the private subnet"
}

variable "drg_id" {
  type        = string
  description = "Shared DRG OCID"
}

variable "drg_route_table_id" {
  type        = string
  description = "Autogenerated VCN route table for the shared DRG"
}

variable "peer_vcn_cidrs" {
  type        = list(string)
  description = "CIDRs of other cluster VCNs reachable through the DRG"
  default     = []
}

variable "reserve_mimir_private_ip" {
  description = "Reserve a stable private IP for the tools Mimir load balancer"
  type        = bool
  default     = false
}

variable "mimir_private_ip_address" {
  description = "Optional fixed private IP for the tools Mimir load balancer"
  type        = string
  default     = ""
}
