apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ../../core/prometheus-collector/operator
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |-
      - op: add
        path: /spec/values/prometheus/prometheusSpec/externalLabels
        value:
          cluster: production
          environment: production
      - op: add
        path: /spec/values/prometheus/prometheusSpec/remoteWrite
        value:
          - url: http://10.10.1.250:8080/api/v1/push
