apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  mimir.yaml: |
    target: all,alertmanager,overrides-exporter
    multitenancy_enabled: false
    no_auth_tenant: anonymous

    server:
      http_listen_port: 8080
      grpc_listen_port: 9095

    usage_stats:
      enabled: false

    blocks_storage:
      backend: filesystem
      filesystem:
        dir: /data/blocks
      tsdb:
        dir: /data/tsdb
        retention_period: 24h
      bucket_store:
        sync_dir: /data/tsdb-sync

    compactor:
      data_dir: /data/compactor
      sharding_ring:
        kvstore:
          store: memberlist

    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester:
      ring:
        replication_factor: 1
        kvstore:
          store: memberlist

    store_gateway:
      sharding_ring:
        replication_factor: 1
        kvstore:
          store: memberlist

    ruler_storage:
      backend: filesystem
      filesystem:
        dir: /data/rules

    alertmanager_storage:
      backend: filesystem
      filesystem:
        dir: /data/alertmanager

    limits:
      ingestion_rate: 100000
      ingestion_burst_size: 200000
      compactor_blocks_retention_period: 7d
