apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  mimir.yaml: |
    target: all,alertmanager,overrides-exporter
    multitenancy_enabled: false
    no_auth_tenant: anonymous

    server:
      http_listen_port: 8080
      grpc_listen_port: 9095

    usage_stats:
      enabled: false

    common:
      storage:
        backend: s3
        s3:
          endpoint: $${MIMIR_S3_ENDPOINT}
          region: sa-saopaulo-1
          access_key_id: $${MIMIR_S3_ACCESS_KEY}
          secret_access_key: $${MIMIR_S3_SECRET_KEY}
          signature_version: v4
          bucket_lookup_type: path

    blocks_storage:
      s3:
        bucket_name: $${MIMIR_S3_BUCKET}
      storage_prefix: blocks
      tsdb:
        dir: /data/tsdb
        retention_period: 24h
      bucket_store:
        sync_dir: /data/tsdb-sync

    compactor:
      data_dir: /data/compactor
      sharding_ring:
        kvstore:
          store: memberlist

    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester:
      ring:
        replication_factor: 1
        kvstore:
          store: memberlist

    store_gateway:
      sharding_ring:
        replication_factor: 1
        kvstore:
          store: memberlist

    ruler_storage:
      s3:
        bucket_name: $${MIMIR_S3_BUCKET}
      storage_prefix: ruler

    alertmanager_storage:
      s3:
        bucket_name: $${MIMIR_S3_BUCKET}
      storage_prefix: alertmanager

    limits:
      ingestion_rate: 100000
      ingestion_burst_size: 200000
      compactor_blocks_retention_period: 30d
