apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mimir-object-storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: oracle-vault
  target:
    name: mimir-object-storage
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        MIMIR_S3_ACCESS_KEY: "{{ .access_key }}"
        MIMIR_S3_SECRET_KEY: "{{ .secret_key }}"
        MIMIR_S3_ENDPOINT: "{{ .endpoint }}"
        MIMIR_S3_BUCKET: "{{ .bucket }}"
  data:
    - secretKey: access_key
      remoteRef:
        key: mimir-s3-access-key
        version: CURRENT
        decodingStrategy: None
    - secretKey: secret_key
      remoteRef:
        key: mimir-s3-secret-key
        version: CURRENT
        decodingStrategy: None
    - secretKey: endpoint
      remoteRef:
        key: mimir-s3-endpoint
        version: CURRENT
        decodingStrategy: None
    - secretKey: bucket
      remoteRef:
        key: mimir-s3-bucket
        version: CURRENT
        decodingStrategy: None
