apiVersion: v1
kind: Service
metadata:
  name: mimir
  annotations:
    oci.oraclecloud.com/load-balancer-type: "nlb"
    oci.oraclecloud.com/reserved-private-ips: "${MIMIR_PRIVATE_IP_ADDRESS}"
    oci-network-load-balancer.oraclecloud.com/internal: "true"
    oci-network-load-balancer.oraclecloud.com/subnet: "${MIMIR_PRIVATE_SUBNET_ID}"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mimir
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: grpc
      port: 9095
      targetPort: grpc
